In [28]:
import numpy as np
import torch

from torch import nn
# from torch import multiprocessing
import multiprocessing
import pickle

In [34]:
pickle.dumps(a)

b'\x80\x03ctorch._utils\n_rebuild_tensor_v2\nq\x00(ctorch.storage\n_load_from_bytes\nq\x01B\xfc0\x00\x00\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x80\x02}q\x00(X\x10\x00\x00\x00protocol_versionq\x01M\xe9\x03X\r\x00\x00\x00little_endianq\x02\x88X\n\x00\x00\x00type_sizesq\x03}q\x04(X\x05\x00\x00\x00shortq\x05K\x02X\x03\x00\x00\x00intq\x06K\x04X\x04\x00\x00\x00longq\x07K\x04uu.\x80\x02(X\x07\x00\x00\x00storageq\x00ctorch\nFloatStorage\nq\x01X\x0e\x00\x00\x0093854648161808q\x02X\x03\x00\x00\x00cpuq\x03M\x00\x0cNtq\x04Q.\x80\x02]q\x00X\x0e\x00\x00\x0093854648161808q\x01a.\x00\x0c\x00\x00\x00\x00\x00\x00\xb8\xf9\x08>\r\x1b2?\xae\xac\x86>\x14(%?\xa2J\x18?4s\x8c>2\xf9\xdc>\x05\x8eW?\x11\x8dJ?A6c?\xba\xf5\\?\xfe\xfb\xb6>&\\k?\xeel]?\xbe\x12\x86>\x00B\x19<\x90\xa5\xb8=\xee\xa0\xc7>\x10\x14\xbc>\x01{Y?J\x90)?F\xfd\xe3>$\x97%>nY\x1c?\xf1\xccF?Nn(?\xb6\xfek?\x04\x96\n?3\xffU?sk\t?\xc4\x1dF>+br?\xcf\t\x10?\xd0 c?\xa8:\xc6>\xd4\x92-?\xe45H>7!m?A\xcf3?\x00>\xb9;\x1b\xe1u?!#\x05?_mY?\x

In [33]:
a = torch.rand(1024, 3)
a

tensor([[0.1338, 0.6957, 0.2630],
        [0.6451, 0.5949, 0.2743],
        [0.4316, 0.8420, 0.7912],
        ...,
        [0.2278, 0.9715, 0.4104],
        [0.5775, 0.8510, 0.1848],
        [0.7411, 0.8743, 0.4522]])

In [25]:
s = reduce_storage(a.storage())[1][1]

In [26]:
s.detach()

57

In [24]:
a.storage()._share_fd_()

(43, 96)

In [15]:
def reduce_storage(storage):
    fd, size = storage._share_fd_()
    df = multiprocessing.reduction.DupFd(fd)
    metadata = (df, size)
    rebuild = None
#     rebuild = rebuild_storage_fd
    
    return (rebuild, (type(storage),) + metadata)

In [ ]:
def reduce_storage():
    fd, size = storage._share_fd_()
    df = multiprocessing.reduction.DupFd(fd)
    cache_key = fd_id(fd)
    metadata = (df, size)
    rebuild = rebuild_storage_fd
    
    return (rebuild, (type(storage),) + metadata)

def rebuild_storage(cls, df, size):
    if sys.version_info[0] == 2:
        while True:
            try:
                fd = multiprocessing.reduction.rebuild_handle(df)
                break
            except OSError as e:
                # Retry on EINTR for platforms that support it
                if e.errno != getattr(errno, 'EINTR', None):
                    raise
    else:
        fd = df.detach()
    try:
        storage = storage_from_cache(cls, fd_id(fd))
        if storage is not None:
            return storage
        storage = cls._new_shared_fd(fd, size)
        shared_cache[fd_id(fd)] = StorageWeakRef(storage)
        return storage
    finally:
        os.close(fd)

In [ ]:
torch.

In [2]:
typecodes = np.ctypeslib._get_typecodes()

NameError: name 'np' is not defined

In [1]:
from multiprocessing import Array

In [3]:
def int_to_bytes(x: int):
    byte_size = (int.bit_length(x) + 8) // 8
    return int.to_bytes(x, length=byte_size, byteorder='big')

In [5]:
int.from_bytes(int_to_bytes(12), byteorder='big')

12

In [6]:
class TwoLayerNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        """
        In the constructor we instantiate two nn.Linear modules and assign them as
        member variables.
        """
        super(TwoLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H)
        self.linear2 = torch.nn.Linear(H, D_out)

    def forward(self, x):
        """
        In the forward function we accept a Tensor of input data and we must return
        a Tensor of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Tensors.
        """
        h_relu = self.linear1(x).clamp(min=0)
        y_pred = self.linear2(h_relu)
        return y_pred

In [17]:
b"Network_" + int_to_bytestring(1)

b'Network_\x01'

In [16]:
int_to_bytestring(128)

b'\x00\x80'

In [9]:
int.to_bytes(12, length=4, byteorder='big')

b'\x00\x00\x00\x0c'

In [2]:
manager = multiprocessing.Manager()

In [4]:
d = manager.dict()

In [6]:
e = manager.Event()

In [8]:
e.is_set()

False

In [5]:
d

<DictProxy object, typeid 'dict' at 0x7fdba8fd9400>

In [5]:
weights = {'t1': t1, 't2': t2}

In [6]:
def test(weights):
    weights['t1'].data[:2, :] = torch.from_numpy(np.random.rand(2, 4).astype(np.float32))

In [7]:
print(t1[:5])
process = multiprocessing.Process(target=test, args=(weights, ))
process.start()
process.join()
print(t1[:5])

tensor([[0.7302, 0.5888, 0.7264, 0.5801],
        [0.6394, 0.2228, 0.7829, 0.6452],
        [0.6523, 0.7329, 0.0077, 0.1489],
        [0.0090, 0.8313, 0.1499, 0.3119],
        [0.3969, 0.0732, 0.2415, 0.0134]])
tensor([[0.9169, 0.1403, 0.4983, 0.2535],
        [0.6777, 0.6849, 0.7462, 0.7037],
        [0.6523, 0.7329, 0.0077, 0.1489],
        [0.0090, 0.8313, 0.1499, 0.3119],
        [0.3969, 0.0732, 0.2415, 0.0134]])


In [25]:
t1

tensor([[1.3103, 0.6176, 0.2781, 0.2319],
        [0.5442, 0.0717, 0.9239, 0.3653],
        [0.0487, 0.5143, 0.4655, 0.7040],
        [0.7518, 0.8226, 0.3952, 0.9089],
        [0.1544, 0.3327, 0.6164, 0.5924],
        [0.4847, 0.7897, 0.9580, 0.8271],
        [0.5833, 0.4050, 0.7880, 0.6106],
        [0.6991, 0.4310, 0.0168, 0.0761],
        [0.0753, 0.3032, 0.5672, 0.4065],
        [0.9160, 0.9159, 0.7107, 0.8792],
        [0.8884, 0.9875, 0.4541, 0.4490],
        [0.1017, 0.9518, 0.5400, 0.1826],
        [0.2967, 0.6562, 0.5817, 0.5010],
        [0.3975, 0.4820, 0.3497, 0.1577],
        [0.0810, 0.8246, 0.4437, 0.2033],
        [0.6491, 0.6743, 0.6639, 0.9179],
        [0.3475, 0.3017, 0.4614, 0.7776],
        [0.8288, 0.4961, 0.2599, 0.3580],
        [0.5064, 0.4028, 0.8753, 0.4936],
        [0.8189, 0.6436, 0.4822, 0.1152],
        [0.4826, 0.8062, 0.3788, 0.8734],
        [0.5797, 0.3920, 0.7408, 0.5955],
        [0.7285, 0.6074, 0.9751, 0.2825],
        [0.4155, 0.7552, 0.1376, 0

In [28]:
a = 1
b = a
a += 1
b

1

In [8]:
torch.dtype

torch.dtype

In [10]:
type(torch.float32)

torch.dtype

In [1]:
from collections import namedtuple

In [1]:
import zmq
from multiprocessing import Process
from time import sleep

In [2]:
context = zmq.Context()
sender = context.socket(zmq.PUSH)
sender.bind("ipc://predict_requests")

In [2]:
import torch
from torch import multiprocessing
from time import sleep

In [2]:
def worker(index, queue):   
    while True:
        d = queue.get()
        d += 1

In [3]:
queue = multiprocessing.Queue()
worker = multiprocessing.Process(target=worker, args=(0, queue), daemon=True)
worker.start()

In [18]:
a = torch.rand(8, 4)
a.share_memory_()

b = torch.rand(8, 1)
b.share_memory_()

c = torch.rand(8, 12)
c.share_memory_()


tensor([[0.0035, 0.3324, 0.7835, 0.7276, 0.1954, 0.0789, 0.3726, 0.9877, 0.2786,
         0.2856, 0.2707, 0.5889],
        [0.7975, 0.9865, 0.9349, 0.4186, 0.0716, 0.4256, 0.2806, 0.4129, 0.6475,
         0.1582, 0.0203, 0.0465],
        [0.8655, 0.0849, 0.3503, 0.7457, 0.4265, 0.3060, 0.5742, 0.8703, 0.3958,
         0.9928, 0.7062, 0.7335],
        [0.2067, 0.3931, 0.5322, 0.2773, 0.7732, 0.6238, 0.8132, 0.5099, 0.6563,
         0.2741, 0.6712, 0.2482],
        [0.1494, 0.7254, 0.5421, 0.7976, 0.3058, 0.3197, 0.4539, 0.0400, 0.3938,
         0.3690, 0.0743, 0.6682],
        [0.8402, 0.6836, 0.4874, 0.9802, 0.8271, 0.7632, 0.3399, 0.0866, 0.9726,
         0.5154, 0.2121, 0.8125],
        [0.5872, 0.8170, 0.6003, 0.7329, 0.6563, 0.8114, 0.3729, 0.2831, 0.7752,
         0.3881, 0.8724, 0.3301],
        [0.5460, 0.8322, 0.8346, 0.7919, 0.7609, 0.6329, 0.8265, 0.2101, 0.7765,
         0.3699, 0.1001, 0.2619]])

In [28]:
event = multiprocessing.Event()
event

In [9]:
lock= multiprocessing.Lock()
lock

<Lock(owner=None)>

In [2]:
import pickle
pickle.dumps(multiprocessing.Queue())

RuntimeError: Queue objects should only be shared between processes through inheritance

In [19]:
data = {'a': a, 'b': b, 'c': c}

In [20]:
buf = io.BytesIO()
ForkingPickler(buf, pickle.HIGHEST_PROTOCOL).dump(data)
val = buf.getvalue()

In [23]:
dat = pickle.loads(val)

In [25]:
dat['a'] += 1

In [22]:
from multiprocessing.reduction import ForkingPickler
import pickle
import io

buf = io.BytesIO()
ForkingPickler(buf, pickle.HIGHEST_PROTOCOL).dump(a)

In [6]:
val = buf.getvalue()
val

b'\x80\x04\x95\x05\x01\x00\x00\x00\x00\x00\x00\x8c torch.multiprocessing.reductions\x94\x8c\x0erebuild_tensor\x94\x93\x94\x8c\x05torch\x94\x8c\x06Tensor\x94\x93\x94h\x00\x8c\x12rebuild_storage_fd\x94\x93\x94h\x03\x8c\x0cFloatStorage\x94\x93\x94\x8c\x1fmultiprocessing.resource_sharer\x94\x8c\x05DupFd\x94\x93\x94)\x81\x94}\x94\x8c\x03_id\x94\x8c$/tmp/pymp-__qj94br/listener-5_p557g1\x94K\x01\x86\x94sbK \x87\x94R\x94(K\x00h\x03\x8c\x04Size\x94\x93\x94K\x08K\x04\x86\x94\x85\x94\x81\x94K\x04K\x01\x86\x94\x89t\x94\x87\x94R\x94.'

In [7]:
c = pickle.loads(val)
c

tensor([[0.0552, 0.0744, 0.7741, 0.6036],
        [0.2920, 0.0800, 0.3155, 0.0188],
        [0.1697, 0.2729, 0.9802, 0.1139],
        [0.3923, 0.1892, 0.5469, 0.1939],
        [0.2792, 0.3746, 0.9684, 0.8010],
        [0.4277, 0.1437, 0.9724, 0.8776],
        [0.8160, 0.5549, 0.0174, 0.4591],
        [0.5295, 0.0308, 0.9904, 0.9223]])

In [9]:
a += 1

In [10]:
c

tensor([[1.0552, 1.0744, 1.7741, 1.6036],
        [1.2920, 1.0800, 1.3155, 1.0188],
        [1.1697, 1.2729, 1.9802, 1.1139],
        [1.3923, 1.1892, 1.5469, 1.1939],
        [1.2792, 1.3746, 1.9684, 1.8010],
        [1.4277, 1.1437, 1.9724, 1.8776],
        [1.8160, 1.5549, 1.0174, 1.4591],
        [1.5295, 1.0308, 1.9904, 1.9223]])

In [1]:
import zmq
from time import sleep
import multiprocessing

def worker(i):
    context = zmq.Context()
    socket = context.socket(zmq.PULL)
    socket.connect('ipc://channel.ipc')
    
    while True:
        print(socket.recv())
        sleep(i)
        
def int_to_bytestring(x: int):
    byte_size = (int.bit_length(x) + 8) // 8
    return int.to_bytes(x, length=byte_size, byteorder='big')

context = zmq.Context()
socket = context.socket(zmq.PUSH)
socket.bind('ipc://channel.ipc')

workers = [multiprocessing.Process(target=worker, args=(i, ), daemon=True) for i in range(4)]
for worker in workers:
    worker.start()

b'hi there \x01'
b'hi there \x02'
b'hi there \x00'
b'hi there \x03'
b'hi there \x04'
b'hi there \x08'
b'hi there \x0c'
b'hi there \x10'
b'hi there \x05'
b'hi there \t'
b'hi there \x06'
b'hi there \r'
b'hi there \x07'
b'hi there \x11'
b'hi there \n'
b'hi there \x0b'
b'hi there \x0e'
b'hi there \x12'
b'hi there \x0f'
b'hi there \x13'


In [2]:
for i in range(20):
    socket.send(b"hi there " + int_to_bytestring(i))

In [5]:
for i in range(20):
    queue.put(f"hi there {i}")

In [1]:
import zmq
from multiprocessing import Process
from time import sleep

In [2]:
def server_in():
    context = zmq.Context()
    
    server_in_front = context.socket(zmq.DEALER)
    server_in_front.setsockopt(zmq.IDENTITY, b'SIF')
    server_in_front.bind('ipc://request_frontend')

    server_in_back = context.socket(zmq.PUSH)
    server_in_back.setsockopt(zmq.IDENTITY, b'SIB')
    server_in_back.bind('ipc://request_backend')
    
    while True:
        zmq.proxy(server_in_front, server_in_back)
        d1 = server_in_front.recv_multipart()
        server_in_back.send_multipart(d1)

In [3]:
def server_out():
    context = zmq.Context()
    
    server_out_back = context.socket(zmq.PULL)
    server_out_back.setsockopt(zmq.IDENTITY, b'SOB')
    server_out_back.bind('ipc://response_backend')

    server_out_front = context.socket(zmq.DEALER)
    server_out_front.setsockopt(zmq.IDENTITY, b'SOF')
    server_out_front.bind('ipc://response_frontend')
    
    while True:
        zmq.proxy(server_out_back, server_out_front)
        d3 = server_out_back.recv_multipart()
        server_out_front.send_multipart(d3)

In [4]:
def network():
    context = zmq.Context()
    
    network_in = context.socket(zmq.PULL)
    network_in.setsockopt(zmq.IDENTITY, b'NI')
    network_in.connect('ipc://request_backend')

    network_out = context.socket(zmq.PUSH)
    network_out.setsockopt(zmq.IDENTITY, b'NO')
    network_out.connect('ipc://response_backend')
    
    while True:
        zmq.proxy(network_in, network_out)
        d2 = network_in.recv_multipart()
        network_out.send_multipart(d2)


In [5]:
si = Process(target=server_in)
so = Process(target=server_out)
n = Process(target=network)

si.start()
so.start()
sleep(0.5)
n.start()

In [6]:
context = zmq.Context()

client_out = context.socket(zmq.DEALER)
client_out.setsockopt(zmq.IDENTITY, b'CO')
client_out.connect('ipc://request_frontend')


client_in = context.socket(zmq.DEALER)
client_in.setsockopt(zmq.IDENTITY, b'CO')
client_in.connect('ipc://response_frontend')

In [7]:
client_out.send_multipart([b"predict", b'dog'])
client_in.recv_multipart()

[b'predict', b'dog']

In [8]:
from time import time

In [9]:
t0 = time()
for _ in range(1000):
    client_out.send_multipart([b"predict", b'dog'])
    
for _ in range(1000):
    out = client_in.recv_multipart()
t1 = time()
print(t1 - t0)

0.03258252143859863


In [3]:
def func():
    return [1, 2, 3, 4, 5]

In [7]:
a, b = func()

ValueError: too many values to unpack (expected 2)

In [8]:
x, y, *z = [1, 2]

In [9]:
z

[]

In [10]:
%%timeit 
for _ in range(2000):
    client_out.send_multipart([b"predict", b'dog'])
    
for _ in range(2000):
    client_in.recv_multipart()

37.9 ms ± 874 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
39.2 / 2000

0.019600000000000003

In [13]:
%%timeit 
client_out.send_multipart([b"predict", b'dog'])
d1 = server_in.recv_multipart()

6.42 µs ± 114 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
%%timeit
server_in.send_multipart([b"NI", *d1])
d2 = network_in.recv_multipart()

9.32 µs ± 611 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%%timeit

In [13]:
%%timeit 
client_out.send_multipart([b"predict", b'dog'])
d1 = server_in_front.recv_multipart()

server_in_back.send_multipart(d1)
d2 = network_in.recv_multipart()


network_out.send_multipart(d2)
d3 = server_out_back.recv_multipart()

server_out_front.send_multipart(d3[1:])
client_in.recv_multipart()

29.1 µs ± 412 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [14]:
30 / 4

7.5

In [14]:
import torch

ModuleNotFoundError: No module named 'torch'

In [4]:
server_in.send_multipart([b"NI", *d1])
d2 = network_in.recv_multipart()
network_out.send_multipart(d2)
d3 = server_out.recv_multipart()
server_out.send_multipart(d3[2:])
client.recv_multipart()

[b'NO', b'', b'B', b'predict', b'dog']

[b'predict', b'dog']

KeyboardInterrupt: 

In [1]:
import zmq

In [2]:
context = zmq.Context()

In [3]:
a = context.socket(zmq.ROUTER)
a.bind("inproc://test")

In [4]:
b = context.socket(zmq.SUB)
b.setsockopt(zmq.SUBSCRIBE, b'')b.connect("inproc://test")

In [5]:
c = context.socket(zmq.DEALER)
c.connect("inproc://test")

In [6]:
b.send(b"hi")

In [7]:
a.recv_multipart()

[b'\x00\xa3\x8e\x1f)', b'hi']

In [9]:
c.send_multipart([b'\x00\xa3\x8e\x1f)', b'bye'])

In [12]:
a.recv()

b'\x00\xa3\x8e\x1f)'